### ISSUE TITLE
Increase time of info box toast messages

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#403] opened 2015-05-03 09:52 UTC
The toast messages used to display info from the **`[i]`** icons on the drawer are shown for too short a time. The actual time shown also seem partially random.  Reproduce by hitting a few in succession.

**Comment by SecUpwN** [comment] 2015-05-05 16:55
It [appears](https://stackoverflow.com/a/2221285) that we cannot increase the time of [LENGTH.LONG](http://developer.android.com/reference/android/widget/Toast.html#LENGTH_LONG). But I also found [Toast-Expander](https://github.com/quiqueqs/Toast-Expander) by @quiqueqs to hack around this limitation. Another solution could be to implement [Crouton](https://github.com/keyboardsurfer/Crouton) by @keyboardsurfer. Experienced users say that hacks should be avoided. Please have a [read](https://stackoverflow.com/questions/2220560/can-an-android-toast-be-longer-than-toast-length-long) to decide.

**Comment by E3V3A** [comment] 2015-05-05 17:24
Just send the toast twice.

**Comment by SecUpwN** [comment] 2015-05-06 14:59
>Just send the toast twice.

This idea has also been covered in linked discussion and is considered as [bad practice](https://stackoverflow.com/questions/2220560/can-an-android-toast-be-longer-than-toast-length-long#comment21261042_6376903):

>This solution is bad because, e.g., if you quit the activity before the time of the toast, it will be blinking over and over..

**Comment by E3V3A** [comment] 2015-05-06 15:07
Ok, how about [this](https://stackoverflow.com/a/28269596/1147688)?

**Comment by SecUpwN** [comment] 2015-05-07 12:21
>Ok, how about this?

Looks much better, feel invited to add it!

**Comment by E3V3A** [comment] 2015-05-07 18:07
Here's the code: 
```java

    public class Toaster {
      private static final int SHORT_TOAST_DURATION = 2000;
      
      private Toaster() {}

      public static void makeLongToast(String text, long durationInMillis) {
        final Toast t = Toast.makeText(App.context(), text, Toast.LENGTH_SHORT);
        t.setGravity(Gravity.TOP | Gravity.CENTER_HORIZONTAL, 0, 0);

        new CountDownTimer(Math.max(durationInMillis - SHORT_TOAST_DURATION, 1000), 1000) {
          @Override
          public void onFinish() {
            t.show();
          }

          @Override
          public void onTick(long millisUntilFinished) {
            t.show();
          }
        }.start();
      }
    }
```
In your application code, just do something like this:
```java
        Toaster.makeLongToast("Toasty!", 8000);
```

**Comment by SecUpwN** [comment] 2015-05-08 08:18
Ok, so [L86-L132](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/f7d56a08eeaf06cba1f7c574147f589ca7912ff9/app/src/main/java/com/SecUpwN/AIMSICD/utils/Helpers.java#L86-L132) of `Helpers.java` would have to be replaced with above code, then we can add `Toaster.makeLongToast("Toasty!", 8000);` into our application code, right? Please correct me if I'm wrong.

**Comment by E3V3A** [comment] 2015-05-08 10:01
You don't need to replace that code, just implement the new.

**Comment by SecUpwN** [comment] 2015-05-08 10:12
>You don't need to replace that code, just implement the new.

Would love to. Where exactly? `Helpers.java`?

**Comment by SecUpwN** [comment] 2015-05-08 10:52
@E3V3A, ok, I've messed it up beautifully. Does the code you linked need to change the "text" to "msg" like in ` final Toast t = Toast.makeText(App.context(), msg, Toast.LENGTH_SHORT);` at all?

**Comment by SecUpwN** [comment] 2015-05-08 14:47
>You don't need to replace that code, just implement the new.

The `Toast Extender` has been implemented and slightly changed. Note: currently not working, I'm still digging around for a fix so that it does not break our builds anymore. We now need to use this:

```JAVA
Toaster.makeLongToast(getApplicationContext()"Toasty!", 8000);
```

**Comment by DimaKoz** [comment] 2015-05-08 21:24
You must use the same instance of "Toaster", otherwise not be able to quickly switch between the content description when you click on another button "i".

**Comment by SecUpwN** [comment] 2015-05-08 21:26
>You must use the same instance of "Toaster"

Please clarify how to do that, @DimaKoz.

**Comment by DimaKoz** [comment] 2015-05-08 21:32
You can use this pattern
http://en.wikipedia.org/wiki/Singleton_pattern#Eager_initialization

**Comment by SecUpwN** [comment] 2015-05-08 22:35
>You can use this pattern...

Thanks. I thought we'd just need to add/replace the code below somewhere into our app?

```JAVA
Toaster.makeLongToast(getApplicationContext()"Toasty!", 8000);
```

**Comment by E3V3A** [comment] 2015-06-01 14:04
I've just tested all info boxes on the main drawer menu, and some are still displayed too short a time, so I reopen this issue until that has been fixed.

**Comment by SecUpwN** [comment] 2015-06-04 04:49
>...and some are still displayed too short a time...

@E3V3A, would you please name the info boxes where this happens so that I can digg into it?

**Comment by E3V3A** [comment] 2015-06-08 13:51
@SecUpwN  Please test on your device.

My tests show strange timing behavior. Clicking [**i**] once, does not show the toast message with the same duration as clicking it a 2nd time. Where are the [**i**] "boxes" implemented?

**Comment by DimaKoz** [comment] 2015-06-08 14:02
Hi @E3V3A
 I think it was  [here] (https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/adapters/DrawerMenuAdapter.java#L53-L56 )

**Comment by SecUpwN** [comment] 2015-06-18 06:31
>My tests show strange timing behavior.

@E3V3A, I don't get these strange behaviors. Do you still have them?

**Comment by E3V3A** [comment] 2015-06-18 07:06
Yes or I would have closed this. As always, unless someone actually fixes the issues, it usually doesn't auto-magically go away. ;)

Affected info boxes: 
```
all, but in an apparently random fashion. API or CPU problem?
```

Apparently, hitting the info boxes slowly and rapidly and randomly give completely different lengths of appearance time. (And no, I'm not hitting them until pop-up is finished displaying.) About 60-70% of the hits give an approximately correct display length. 

I'm not sure we can do anything about this issue without digging deeper into how the API schedules Apps and threads. Thus we probably cannot expect to trust programmed timers, unless running as root and system process...

So unless someone has a better explanation, we can probably close this issue and add it as documentation status.

**Comment by SecUpwN** [comment] 2015-06-18 10:07
>So unless someone has a better explanation, we can probably close this issue and add it as documentation status.

@DJaeger, do you have a better explanation for this?

**Comment by DJaeger** [comment] 2015-06-18 22:24
Will look into

**Comment by SecUpwN** [comment] 2015-06-21 12:56
>Will look into

Any news on this @DJaeger? ;-)

**Comment by DJaeger** [comment] 2015-06-22 13:55
The [i] toast are not using msgLong, but the default setText of toast class.
Because of that they are shown the deffault 3.5 seconds.
I can see different behaviors for the [i] toasts.

**Comment by SecUpwN** [comment] 2015-06-22 14:25
>The [i] toast are not using msgLong, but the default setText of toast class.

Ok, would changing [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/adapters/DrawerMenuAdapter.java#L53-L56) to the following fix this Issue? If so, let me know and I'll do it.

```JAVA
 private void showHelpToast(Integer pToastValueId) {
mToast.msgLong(getContext().getString(pToastValueId));
mToast.show();
}
```

**Comment by DJaeger** [comment] 2015-06-23 05:33
The new implementation seems to doesn't support to cancel the current toast for new one.
So if I want to read all info boxes I have to wait the full time for every box, because the click on a new infobox is queued and doesn't trigger a direct text change.

**Comment by E3V3A** [comment] 2015-06-23 06:55
Actually the queue is LIFO. Or last entered, first shown.

**Comment by SecUpwN** [comment] 2015-06-23 07:09
>Every toast is now visible for 6 seconds, whatever you do.

Was this this the effect you desired, @E3V3A?

>The new implementation seems to doesn't support to cancel the current toast for new one.

Not sure if this has been the case before, but every toast of our app is now appearing at the very top of my screen, whereas other apps display toasts in the *center* of the screen. Can we change it to that?

**Comment by DJaeger** [comment] 2015-06-23 08:14
@E3V3A It's not LIFO for me!?
@SecUpwN:
>> Every toast is now visible for 6 seconds, whatever you do.

> Was this this the effect you desired, @E3V3A?

I think not, as we wanted to change it, if a new icon is clicked.
We have to implement a Singleton for this as @DimaKoz mentioned.


For me other apps display the toast at the bottom.
We can change that behavior be changing
```
t.setGravity(Gravity.TOP | Gravity.CENTER_HORIZONTAL, 0, 0);
```
to (for vertically centered toast):
```
t.setGravity(Gravity.CENTER_VERTICAL | Gravity.CENTER_HORIZONTAL, 0, 0);
```
or (for toast at the bottom)
```
t.setGravity(Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL, 0, 0);
```

**Comment by SecUpwN** [comment] 2015-06-23 08:25
>For me other apps display the toast at the bottom.

I am comfortable with either bottom or center, whichever is better to be seen.

>We have to implement a Singleton for this as @DimaKoz mentioned.

Not sure if he is still around, haven't heard a thing of him in a long time..

**Comment by DJaeger** [comment] 2015-06-23 09:04
This should do all the magic:

```java
public class Toaster {

    private static final int SHORT_TOAST_DURATION = 2000;
    private static final long TOAST_DURATION_MILLS = 6000; //change if need longer

    // Private constructor. Prevents instantiation from other classes.
    private Toaster() { }
 
    /**
     * Initializes singleton.
     *
     * ToasterHolder is loaded on the first execution of Toaster.getInstance()
     * or the first access to ToasterHolder.INSTANCE, not before.
     */
    private static class ToasterHolder {
        private static final Toaster INSTANCE = new Toaster();
    }
 
    public static Toaster getInstance() {
        return ToasterHolder.INSTANCE;
    }

    /**
     * Long toast message
     * TOAST_DURATION_MILLS controls the duration
     * currently set to 6 seconds
     * @param context Application Context
     * @param msg     Message to send
     */
    public static void msgLong(final Context context, final String msg) {
        if (context != null && msg != null) {
            final Toast t = Toast.makeText(context, msg, Toast.LENGTH_SHORT);
            t.setGravity(Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL, 0, 0);

            new CountDownTimer(Math.max(TOAST_DURATION_MILLS - SHORT_TOAST_DURATION, 1000), 1000) {
                @Override
                public void onFinish() {
                    t.show();
                }

                @Override
                public void onTick(long millisUntilFinished) {
                    t.show();
                }
            }.start();
        }
    }
    /**
     * Short toast message
     * (Predefined in AOS to 2000 ms = 2 sec)
     *
     * @param context Application Context
     * @param msg     Message to send
     */
    public static void msgShort(final Context context, final String msg) {
        if (context != null && msg != null) {
            new Handler(context.getMainLooper()).post(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(context, msg.trim(), Toast.LENGTH_SHORT).show();
                }
            });
        }
    }
}
```

With that you call
```
Toaster.getInstance().msgLong(context.getApplicationContext(), context.getApplicationContext().getString(pToastValueId));
```

**Comment by DJaeger** [comment] 2015-06-23 09:05
If that solution is ok for you, I will create a PR.

**Comment by SecUpwN** [comment] 2015-06-23 09:55
>If that solution is ok for you, I will create a PR.

Great! Where does the toast get displayed now? Yes, please craft a PR so that we can test this.

**Comment by DJaeger** [comment] 2015-06-23 12:49
With this change the toasts will be at the bottom.
This class and its methods should replace all the existing toasts, so I will also replace all toast to use one of them!

Please check if you really see short messages at the top or centered.
If so I will change msgShort to force them at the bottom, to have them all at the same position.

**Comment by SecUpwN** [comment] 2015-06-23 16:05
>...so I will also replace all toast to use one of them!

I do not quite get what you mean by that.

>Please check if you really see short messages at the top or centered.

The normal toasts when loading up our app (like granted SuperSU permissions and starting of services related to AIMSICD) appear at the bottom. When pressing the `[ i ]`, they all appear at the top.

>If so I will change msgShort to force them at the bottom, to have them all at the same position.

If there is a "standard" on where they should be displayed, I'd go with that. Otherwise all other apps do display it either at the bottom or in the center, it seems. If you ask me, I'd always prefer the **center**.

**Comment by E3V3A** [comment] 2015-06-24 00:13
I also prefer bottom or center, not to cover other info. Also regarding LIFO, mentioned above, was that the last **[i]** pushed would always show immediately (AOS 4.2.2 API 19) and then the previously pushed one, if interrupted...

**Comment by DJaeger** [comment] 2015-06-24 06:35
>The normal toasts when loading up our app (like granted SuperSU permissions and starting of services related to AIMSICD) appear at the bottom. When pressing the [ i ], they all appear at the top.

Ok, that's what I wanted to know.
So the default is bottom for you, too.
It sounds in a previous answer as centered is the default on your phone.

>I also prefer bottom or center, not to cover other info.

Thats the reason I would prefer bottom, which is also the default.

>Also regarding LIFO, mentioned above, was that the last [i] pushed would always show immediately (AOS 4.2.2 API 19) and then the previously pushed one, if interrupted...

It's not so for me.
I think the behavior changed with newer Android.
But this should also be solved with the Singelton I will do.

**Comment by SecUpwN** [comment] 2015-06-24 11:15
>But this should also be solved with the Singelton I will do.

Awesome, confirming this Issue as finally being **solved**! :white_check_mark: 
@E3V3A, since this is your Issue, please confirm and close it.

**Comment by DJaeger** [comment] 2015-06-24 12:05
Its not completly what expected.
By clicking on a info button the currently shown toast should be canceled and the new one shown.
And also the position is a different.
I will rework this.
But the core of this issue should be solved.

**Comment by DJaeger** [comment] 2015-06-25 07:46
It's now working like expected.
The toast is now at the correct position and is immediately replaced by a new one.
This works for short and long messages.
@E3V3A please confirm

**Comment by SecUpwN** [comment] 2015-06-25 18:02
>The toast is now at the correct position and is immediately replaced by a new one.
>This works for short and long messages.

Confirmed. Working and looking beautifully!

**Closed by SecUpwN** 2015-06-25 18:02 UTC
Labels: BUG, REMEMBER_THIS
