### ISSUE TITLE
CellTracker looking for NCs even if nc_list_present is false

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#548] opened 2015-07-14 18:43 UTC
Also see #100 and #264 for reference.

Apparently the [CellTracker]() keep on looking for NCs even if **`nc_list_present`** is set to **false**. Creating lots of unnecessary logs trying to re-poll NC list.

```
I/AIMSICD ( 4545): CellTracker: neighbouringCellInfo empty - start polling
I/CellTracker( 4545): Cell info change
D/AIMSICD ( 4545): CellTracker: neighbouringCellInfo empty: trying 0
```

In addition, [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/22c0ca07599b0d62ec7816f3fcce27bfe33da9d6/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L537-L540) is wrong behavior:
```java
Update: from banjaxbanjo
    I removed the timer that activated this code and now the code will be run when
    the cell changes so it will detect faster rather than using a timer that might
    miss an imsi catcher, also says cpu rather than refreshing every x seconds.
```
The code should run:
 - 1. Immediately if there's been a network change
 - 2. at a polling time interval X when there is no network change.

Wait a second...this seem too familiar...

**EDIT!**

Holy Shit! (Seem like previous PRs have been over written!) See my previous PR here: d590e2ea774750d12177d9151d12ddf86b4b8b42  and compare to yours [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/de3c3a437bea1f64913f234e23e5cd64068ea20d#diff-9386af9ad86862d793ce1c985d760bab)...

@banjaxbanjo Why wasn't repo synced before PR!? We had a code freeze...

**Comment by banjaxbanjo** [comment] 2015-07-14 18:58
@E3V3A it was synced the celltracker I was working on was  the same as new one so I copied my version  (apparently not) can you tell me what the problem is and I will sort it? 

So I need to stop checking for nc phone doesnt support it.

We discussed first issue about timer already but my PR was mostly for DB not this issue

**Comment by E3V3A** [comment] 2015-07-14 19:05
@banjaxbanjo Yeah, look funny, because *your* PR contain some of the changes of *my* PR, but other changes has been reverted. Please compare the two links above.

**Comment by banjaxbanjo** [comment] 2015-07-14 19:11
@E3V3A here is the class before my pr eva

https://github.com/E3V3A/woork/blob/development/CellTracker1.java

I was going by changelog on the class and I thought it was touched since my last pr so my bad. I'll merge original back with my changes soon.

**Comment by E3V3A** [comment] 2015-07-14 19:17
Ok, so perhaps it's actually my fault. That is certainly not the same as the one in dev repo here. Seem that I've copy pasted the wrong (old) code, from blob hash. Dammit! 

To fix, I guess we need to re-instate the stuff from the "*my*" PR above... as for the other code I have no idea...

**Comment by banjaxbanjo** [comment] 2015-07-14 19:21
@E3V3A no I say my class was a little older I will merge class on your repo with my changes so should be back to original behaviour.

**Comment by E3V3A** [comment] 2015-07-14 19:23
Huh?
No wait, what are you doing? Don't use stuff from my repo...

**Comment by banjaxbanjo** [comment] 2015-07-14 19:29
@E3V3A lol I know that eva but in your work folder we put the original celltracker from latest dev before we started working on merging code. The one I had offline was older than this so I need to put my changes into that original.

**Comment by E3V3A** [comment] 2015-07-14 19:35
Ok, because there are other CellTracker changes made before my commit linked above, so i have no idea where your stuff starts and ends... Go ahead and make a CellTracker fix PR, and we'll simply see what happens.

**Comment by E3V3A** [comment] 2015-07-14 19:54
@banjaxbanjo 

We have the same problem in sevreal other files. They were out dated versions... I have no idea how to track this back, but I just went through your DB UPDATE PR again...and found other inconsistencies...

**Comment by E3V3A** [comment] 2015-07-14 22:53
We need to backtrack every single java file in your PR to see if it was up-to-date before PR. I think we're looking at about 8-9 days back.

**Comment by banjaxbanjo** [comment] 2015-07-14 23:04
AIMSICDDbAdatper.java
CellTracker.java
RequestTask.java
Db veiwer

These are the main files Ive worked on most of the others are new files
 Map view is original with minor changes

**Comment by E3V3A** [comment] 2015-07-14 23:10
I've made changes to DB viewer today, and probably none for a long time before your PR, so perhaps its ok.

**Comment by banjaxbanjo** [comment] 2015-07-14 23:16
This is my fault for the outdated classes and I went over before copying mine over so just email me what needs fixing and I will sort asap. CellTracker requesttask classes are the ones not 100% up to date other's should be fine.

**Comment by SecUpwN** [comment] 2015-07-15 05:42
>We need to backtrack every single java file in your PR to see if it was up-to-date before PR. I think we're looking at about 8-10 days back.

WTF is this mess going on here, guys? Do we need to revert the whole database overhaul?

**Comment by banjaxbanjo** [comment] 2015-07-15 07:16
No it can be fixed only celltracker and request task not completely up to date. All this can be sorted I dont see the big deal it was 3000+ lines of code we where going to have issues. It was my fault celltracker and request task not 100% I thought code looked identical so I copied mine over. MiscUtils I removed unneeded codee and had to chamge timestamp format. Mirror problems with that.

**Comment by SecUpwN** [comment] 2015-07-15 07:26
>No it can be fixed only celltracker and request task not completely up to date.

Thank you for clarifying. Hope you don't break apart given all the things E:V:A is requesting. Take a break any time you like and get in touch with me via E-Mail if you feel you need to talk. Keep rocking! :guitar:

**Comment by banjaxbanjo** [comment] 2015-07-15 07:38
There is nothing major missing only a few comments and a boolean check to display nc list from what I can see. Everything can be fixed in my opinion and this ocid error was present before me pr amd the funny is when I tried the get key last night it worked perfect. (Weird)

**Comment by SecUpwN** [comment] 2015-07-15 08:20
>Everything can be fixed in my opinion and this ocid error was present before my pr

I can confirm that the OCID error was presnt *before* your pull request. Not your fault.

>and the funny thing is when I tried the get key last night it worked perfect. (Weird)

If you ask me, the OCID service is messed up somehow. Maybe a side-effect of their data cleansing?

**Comment by DJaeger** [comment] 2015-07-15 08:40
Sounds like OCID servers were slow due to their cleaning.

**Comment by E3V3A** [comment] 2015-07-15 09:42
I increased the timeout to 80 secs, but I think that also was a commit the was reverted in DB PR... You need to check, as I don't have any time today. Just on my phone...

**Comment by banjaxbanjo** [comment] 2015-07-15 09:47
@E3V3A this time out is still 80 seconds and I've crossed checked the celltracker from 10 days ago and there was very little changes only only formatting so I dont understand what the big issue is with CellTracker I've emailed you on the details of whats been changed and removed

**Comment by E3V3A** [comment] 2015-07-15 09:55
Ok, I'll look at email, but will not be able to respond for 2 days... I'm very busy elsewhere right now. I believe what you say.

**Comment by banjaxbanjo** [comment] 2015-07-15 09:57
No Problem, there is no major issues here and only minor stuff like comments from what I see everything else can be sorted.

**Comment by DJaeger** [comment] 2015-07-15 13:29
except of this line it is simply reformatting in ```d590e2ea774750d12177d9151d12ddf86b4b8b42```:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/d590e2ea774750d12177d9151d12ddf86b4b8b42#diff-9386af9ad86862d793ce1c985d760babR708

But this commit is much more relevant:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/75ec459ff4920b251c1a3ceb0c95900f265f4a98

**Comment by E3V3A** [comment] 2015-07-23 10:38
@banjaxbanjo Can we close this? Please post what PR fixed it. Thanks.

**Comment by banjaxbanjo** [comment] 2015-07-23 10:56
@E3V3A this was the fix eva
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/d6f9e22d338a83678d927e6eb5e7f9cfbea6d19d

**Comment by E3V3A** [comment] 2015-07-23 11:23
Thanks

**Closed** 2015-07-23 11:23 UTC
Labels: BUG, URGENT
