### ISSUE TITLE
Graphical glitch and potential crash in settings

### ISSUE THREAD

**Issue by vanitasvitae** [SecUpwN/Android-IMSI-Catcher-Detector#741] opened 2016-01-04 16:30 UTC
I discovered, that there is a graphical glitch when you go into the settings, then switch to androids recent apps overview and back to AIMSICD again. It looks like the textual elements of the settings activity get duplicated. Also the app once crashed for me after this happened.

**Comment by vanitasvitae** [comment] 2016-01-04 16:44
EDIT: AMISICD crashes, when you do the steps mentioned above to get the graphical glitch and then press the phones back button. Here are some logs:

01-04 17:36:04.237 14986 14986 E QSEECOMD: : Listener: index = 0, hierarchy = 0
01-04 17:36:04.237 14986 14986 E QSEECOMD: : Init dlopen(librpmb.so, RLTD_NOW) is failed....
01-04 17:36:04.237 14986 14986 E QSEECOMD: : ERROR: RPMB_INIT failed, shall not start listener services
01-04 17:36:05.056 14526 14526 E InputEventSender: Exception dispatching finished signal.
01-04 17:36:05.056 14526 14526 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.ListView.getSelectedItem()' on a null object reference
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.preference.PreferenceFragment$3.onKey(PreferenceFragment.java:413)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.View.dispatchKeyEvent(View.java:9236)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1635)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.widget.ListView.dispatchKeyEvent(ListView.java:2144)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.app.Activity.dispatchKeyEvent(Activity.java:2731)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:323)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:135)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-04 17:36:05.057 14526 14526 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-04 17:36:05.057 14526 14526 D AndroidRuntime: Shutting down VM
01-04 17:36:05.058 14526 14526 E AndroidRuntime: FATAL EXCEPTION: main
01-04 17:36:05.058 14526 14526 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 14526
01-04 17:36:05.058 14526 14526 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.widget.ListView.getSelectedItem()' on a null object reference
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.preference.PreferenceFragment$3.onKey(PreferenceFragment.java:413)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.View.dispatchKeyEvent(View.java:9236)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1635)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.widget.ListView.dispatchKeyEvent(ListView.java:2144)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:2395)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1727)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.app.Activity.dispatchKeyEvent(Activity.java:2731)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:323)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-04 17:36:05.058 14526 14526 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


01-04 17:36:07.627 14991 14991 D AndroidRuntime: Shutting down VM
01-04 17:36:07.628 14991 14991 E AndroidRuntime: FATAL EXCEPTION: main
01-04 17:36:07.628 14991 14991 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 14991
01-04 17:36:07.628 14991 14991 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.fragments.DeviceFragment.updateUI(DeviceFragment.java:125)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.fragments.DeviceFragment.access$200(DeviceFragment.java:34)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.fragments.DeviceFragment$1.onServiceConnected(DeviceFragment.java:91)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-04 17:36:07.628 14991 14991 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by SecUpwN** [comment] 2016-01-05 17:29
Thanks for filing this, @vanitasvitae. Your Issue is in fact a dupe of #712. Please help us there.

**Closed by SecUpwN** 2016-01-05 17:29 UTC
Labels: BUG, DUPLICATE
