### ISSUE TITLE
Constant 'Error retrieving OpenCellID data.'

### ISSUE THREAD

**Issue by darkerego** [SecUpwN/Android-IMSI-Catcher-Detector#420] opened 2015-05-06 20:01 UTC
Hey, I wanted to let you know about this error I have been getting. It may be a problem on opencellid's end and not the fault of the app, I don't know. Over the last two weeks or so, I am getting this error ( 'Error retreiving opencellid data, check your network') more frequently than not when I try to download the local BTS data. There is nothing wrong with my network connection, and it happens whether I am on WiFi, mobile data, proxied through tor, or various vpn servers. However, I am always able to upload data to opencellid without issue. This appears to affect all releases (at least for me). I don't see anything in the debug logs that explains the problem. I can see from netstat that the app is connecting to an Opencellid server in Germany. It happens quite arbitrarily, and sometimes after trying two or three times it will finally work and display "opencellid data succesfully retrieved". I wonder if the wrong error message is being displayed? Perhaps it is failing to retrieve the data for different reasons?

**Comment by SecUpwN** [comment] 2015-05-06 20:09
Good evening @darkerego. To classify whether this is really a bug within our app, please really follow our guide on how to [correctly submit Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues). Without any logfiles, we cannot help at all! Thank you.

**Comment by darkerego** [comment] 2015-05-06 20:33
SecUpwN, the device is Motorola E (condor), running CyanogenMod (12.1-20150503-NIGHTLY-condor), baseband version MSM8610BP_1034.307.26.01P, kernel version 3.4.42-g3f377a3. I posted a logcat with aimsicd entries here: https://defuse.ca/b/3PIPiXWy and sent the decryption password to your email address. Thanks.

**Comment by SecUpwN** [comment] 2015-05-07 02:32
Thank you for sending the logfile. I decrypted it and had a look, but I am wondering if you filtered the log since it seems that the actual error you've described in here is not in there. This is all I found in there:

> W/System.err( 2452): at com.SecUpwN.AIMSICD.utils.RequestTask.doInBackground(SourceFile:203)
 >W/System.err( 2452): at com.SecUpwN.AIMSICD.utils.RequestTask.doInBackground(SourceFile:90)

Should you have filtered the logcat, please send me a full logcat.

**Comment by darkerego** [comment] 2015-05-07 07:07
Hey,

Yes I grepd the aimsicd entries, sorry I am not too experienced with
Android debugging. Would you mind sending me a gpg key and i will
encrypt the full log and send it to you?

**Comment by SecUpwN** [comment] 2015-05-07 07:29
>Would you mind sending me a gpg key and i will encrypt the full log and send it to you?

Have a look into your inbox.

**Comment by SecUpwN** [comment] 2015-05-07 08:32
>Would you mind sending me a gpg key and i will encrypt the full log and send it to you?

Done. @darkerego, I have found entries of `Xprivacy` in your logfiles. Are you sure you've set the correct [permissions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Permissions)? Since you have a license for it, you may also automatically download the crowd sourced restrictions. Please do me the favor and send another logfile created with the button `Debugging`.

**Comment by E3V3A** [comment] 2015-05-07 08:40
The code that generate that message is [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/729a4f4aceff6230c525b2650867a6af7f811cce/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L319-L352) So I think there are only two ways that this can happen:

 1. There is a time delay somewhere for already downloaded success.
 2. There is a significant network lag somewhere between your phone and OCID server, that time-out the request. I don't know where this is done in the API, so this would need considerable more investigation, which means its unlikely that we will bother to resolve this, unless there are many more people with the same issue. 

Hmm, looks like there are 2 different timout settings [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/729a4f4aceff6230c525b2650867a6af7f811cce/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L97-L98). Why is that?

```java
public static final int REQUEST_TIMEOUT_MAPS = 20000;       // [ms] 20 s Calling from map
public static final int REQUEST_TIMEOUT_MENU = 40000;       // [ms] 40 s Calling from menu
```
The timeout is set [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/729a4f4aceff6230c525b2650867a6af7f811cce/app/src/main/java/com/SecUpwN/AIMSICD/utils/RequestTask.java#L203-L204):

```java
urlConnection.setConnectTimeout(mTimeOut);
urlConnection.setReadTimeout(mTimeOut);   // [ms] 20 s
```
Perhaps @agilob can have a look at this issue? (The last person who made some changes here.)

**Comment by darkerego** [comment] 2015-05-07 09:15
I have xprivacy installed because I bought it when I was on KK, but it does not work on L yet so I am not using it, it should not even be enabled.  I was connected to a vpn overseas when I took that logcat, so that may account for the delay, but it also happens over straight wifi as well. I will you send another log file in the morning as I am about to go to bed. Thanks for looking into this.

**Comment by E3V3A** [comment] 2015-05-07 10:28
Trying to download data over VPN is a bad idea. Too long TTL ping times.

**Comment by darkerego** [comment] 2015-05-07 18:45
Well I just took another logcat as requested, tried downloading 3 times, once over VPN, and twice over WiFI. I think it failed all 3 times. I sent the log to SecUpwN. I also exported my db to sd so you can see what's going on with that too.

**Comment by SecUpwN** [comment] 2015-05-08 05:21
>I think it failed all 3 times. I sent the log to SecUpwN.

Thanks. I forwarded your logfiles to E:V:A so that he can have a look as well. Stay tuned.

**Comment by darkerego** [comment] 2015-05-08 06:03
Okay. After about two weeks, the situation was not as bad today, It only failed once this morning. If it continues to work I will let you know.

**Comment by E3V3A** [comment] 2015-05-08 14:24
I got a logcat today, and there's not a single newline in there. It's bloody impossible to read logs without newlines or carriage return in them.

**Comment by SecUpwN** [comment] 2015-05-08 14:40
>I got a logcat today, and there's not a single newline in there.

Sorry @E3V3A, it was my fault. I've sent you a new copy.

**Comment by E3V3A** [comment] 2015-05-08 14:55
Ok @darkerego,  I had a look at your logcat, and my first impression is that this is not related AIMSICD, but to CM. There are basically no errors from AIMSICD, but hundreds from your CM distro. In addition, seeing that you're using AT&T perhaps you're on a CDMA network? (We don't support all CDMA functions yet.) Second, the logcat is rather unusable, since it's impossible to tell from it where the error you describe occurs. If you want to be of help, you have to clear logcat right before the error and stop it (export the file) immediately after your error. (I've described this already, elsewhere, even posted a script so you can just hit a key.) You have to descibe in detail your device, and what you do to reproduce your error. Sorry, I don't have time to look at this. 

@SecUpwN I suggest we just increase the time-out for the map download to 40s.

**Comment by SecUpwN** [comment] 2015-05-08 15:05
>I suggest we just increase the time-out for the map download to 40s.

Accepted and noted down. I will close this Issue with the new timeout then.

**Comment by darkerego** [comment] 2015-05-08 17:05
Huh... yeah it is alpha CM, but I didn't know it was that unstable! Yes, AT&T's 3G networks are WCDMA networks. Aren't most HSPDA+ networks WCMDA these days? I played around with the itpables on my VPN and updated to a new nightly, and things seem to be back to normal. I have not had an issue getting the data to download since yesterday morning. Increasing the timeout or doing whatever to make the app proxy friendly is probably a good idea. Okay I think it's safe to say this was the fault of CM and not your app.

**Closed** 2015-05-08 18:18 UTC
Labels: BUG
