### ISSUE TITLE
Crashing on Nexus 5 Android 6.0.1 version (1.37)

### ISSUE THREAD

**Issue by kupru** [SecUpwN/Android-IMSI-Catcher-Detector#737] opened 2016-01-02 03:14 UTC
Everytime location is on 'high accuracy' it works but when in 'battery saving' app crashes.

**Comment by SecUpwN** [comment] 2016-01-02 21:19
Hi there, @kupru! This in fact a dupe of #688 and you are not using our latest release. Pleas do so.

**Closed** 2016-01-02 21:19 UTC
Labels: BUG, DUPLICATE
