### ISSUE TITLE
Settings Bug: Stationary Overlay

### ISSUE THREAD

**Issue by Walkman100** [SecUpwN/Android-IMSI-Catcher-Detector#712] opened 2015-12-27 15:16 UTC
Reproducible 100%:
- open preferences
- select Detection strings option
- tap back button

After doing the above, the preferences menu has a stationary overlay that goes away after closing and opening it:
![screenshot_2015-12-27-15-52-45](https://cloud.githubusercontent.com/assets/5454764/12010767/69989e28-acbc-11e5-90ed-8672f94f1f17.png)

Latest version on F-droid

**Comment by SecUpwN** [comment] 2015-12-27 15:21
Thanks for filing this, @Walkman100. I can confirm this Issue as well. We'll be adding a new way of collecting quality debugging logs soon, so please be patient a little. Seeking more UI/UX developers.

**Comment by Tonat-Systems** [comment] 2016-01-03 18:45
Experiencing the same when clicking "request OCID key" and then returning to preferences.

**Comment by SecUpwN** [comment] 2016-01-05 17:19
>Experiencing the same when clicking "request OCID key" and then returning to preferences. 

Welcome back, @Tonat! We're currently working on a custom implementation of `bugsnag` to hopefully cut down on the piled bugs in the future. Meanwhile, we'd be happy to receive some fixing pull requests.

**Comment by NezSpencer** [comment] 2016-01-11 07:57
Wanted to file this issue too before I noticed its been filed already.

**Comment by SecUpwN** [comment] 2016-01-11 08:00
>Wanted to file this issue too before I noticed its been filed already. 

@NezSpencer, are you able to see if you can find and fix the cause of this as well?

**Comment by NezSpencer** [comment] 2016-01-11 08:16
@SecUpwN havnt found a fix yet but I am trying to

**Comment by SecUpwN** [comment] 2016-01-11 08:25
>@SecUpwN havnt found a fix yet but I am trying to

Thanks, I very much appreciate your effort, @NezSpencer.

**Comment by NezSpencer** [comment] 2016-01-12 12:20
@SecUpwN  @larsgrefer please check [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/748)

**Comment by larsgrefer** [comment] 2016-01-12 12:49
fixed by #748

**Closed by larsgrefer** 2016-01-12 12:49 UTC
Labels: BUG, UI/UX
