### ISSUE TITLE
location / signal in aimcid_locationinfo.csv not updated while the cell is not changing

### ISSUE THREAD

**Issue by kolg** [SecUpwN/Android-IMSI-Catcher-Detector#299] opened 2015-01-24 02:49 UTC
Hello,

the bug must be there since WIP-Release v0.1.25-alpha-build-9, i'm using -15 now.

I did the following: tracking cells enabled, i collected measurements around the city. Then i used the backup-function and copied the aimcid_locationinfo.csv to my computer. I noticed that the fields in "_id","Lac","CellID" and "Timestamp" are correct, but "Lat","Lng" and "Signal" are not updated until the cell is changing. So I get a lot of lines each with the same cell, signal and location. Before version build-9 the values are alright.

I can't check if the values are wrong in the internal database because the app crashes when i try to load "measured signal strengths" in the database menu. maybe the file is too big? (about 8700 measurements, the .csv is about 1,5MB in size)

Hardware: Fairphone FP1, OS Cherry 1.6 (Android 4.2.2)
AIMSICD version v0.1.25-alpha-build-15

**Comment by SecUpwN** [comment] 2015-01-24 13:51
Good evening @kolg, thank you for joining our Project! Would you please reproduce the error you've described above and send us the link to your logcat pasted on [PIE BIN](https://defuse.ca/pastebin.htm), please? We will have a look.

**Comment by kolg** [comment] 2015-01-25 01:27
Hello,
i suspect that you mean the logcat output of the crash? I'll do that in a separate issue because it seems to me that this is not related to the non-updated location/signal values.
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/300

Here I could give you my output .csv if you want, but i'd rather send that privately because of all the geodata included.

**Comment by E3V3A** [comment] 2015-01-25 18:19
@kolg Was this fixed in b23? In addition what you say here is kind of a duplicate of #284.

**Closed by E3V3A** 2015-01-25 18:19 UTC
Labels: BUG, DUPLICATE
