### ISSUE TITLE
Integration of GPL SnoopSnitch IMSI Detection

### ISSUE THREAD

**Issue by Ste4thOverride** [SecUpwN/Android-IMSI-Catcher-Detector#415] opened 2015-05-05 03:24 UTC
Common IMSI Catcher Techniques:

1. When a phone shifts from a more-secure 3G network to a less-secure 2G one
2. When a phone connection strips away encryption
3. When a cell tower fails to make available a list of other cell towers in the area (neighbor’s list)

SnoopSnitch is GPL and has detection for many of theses and other features including detection of tampering with SS7. If you can please add support for the above three features, I know some of the features are already built in but much more could be added by building in the already SnoopSnitch functionality.

**Comment by SecUpwN** [comment] 2015-05-05 04:31
Good morning @Ste4thOverride, thank you for participating in our project and wanting to make this a one-stop kick-ass app! We're working on it as best as possible. ;-) This is in fact a dupe of #241, but here is my suggestion: Please do us the favor and read our note on [similar projects](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Similar-Projects), this will make it clear for you who wanted to work together and who refused to do so. Furthermore, the detection methods you bring up here are completely covered in #230. I'm closing this one now, feel invited to develop with us!

**Closed** 2015-05-05 04:31 UTC
Labels: DUPLICATE, QUESTION

**Comment by Ste4thOverride** [comment] 2015-05-06 01:17
I see the SnoopSnitch Project listed but the software is GPL and open to incorporate freely if if the project team members won't help on the project.
