### ISSUE TITLE
Hide "Status: Good" notifications

### ISSUE THREAD

**Issue by mikael-fourrier** [SecUpwN/Android-IMSI-Catcher-Detector#374] opened 2015-04-17 10:31 UTC
I can't find a way to mask the notification when no IMSI-Catcher is detected. If it was possible, the impact of seeing the notification would be greater.

**Comment by SecUpwN** [comment] 2015-04-17 10:43
Excuse me please, but I really don't get what you're trying to achieve. Please clarify.

**Comment by mikael-fourrier** [comment] 2015-04-17 11:26
Sorry.
When the application is running, there is a notification which indicates if there is an IMSI catcher nearby. This notification could be hided if there is no catcher detected.

**Comment by SecUpwN** [comment] 2015-04-17 11:34
@mikael-fourrier, we are currently still in [ALPHA stage](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status#alpha-stage) and simply lack pull requests for fixing most of the Issues we discovered. Could it be that your Issue here is in fact a duplicate of #349?

**Comment by mikael-fourrier** [comment] 2015-04-17 11:39
Not really, they talk about the database correctness, I talk about the interface.

**Comment by SecUpwN** [comment] 2015-04-17 11:52
>This notification could be hided if there is no catcher detected.

Which indication do you mean? The yellow warning? Please add a screenshot.

>Not really, they talk about the database correctness, I talk about the interface.

See, the yellow warning should only come up if the CID does not exist in the OCID DB.

**Comment by mikael-fourrier** [comment] 2015-04-17 12:06
Yes, I mean the green one. Most of the time (I hope), there is no catcher nearby, so it's not really useful to keep the notification visible all the time.
Sorry for the imprecision.

**Comment by SecUpwN** [comment] 2015-04-17 12:20
>Sorry for the imprecision.

No worries, better late than never. ;-) I would like to hear the opinion of @He3556 on this one as well, but since our app is all about indicating every single thing, even the loading procedure (see the [Status Icons](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Status-Icons)), I guess this Issue really is not so important and does not improve anything. Other than that, I do think it is also dangerous hiding the notification. Imagine the case where the green status has been hidden: How do you know if the app is running? And what would happen if the status would change, but you wouldn't see it since for some reason the code for hiding the green status has been messed up or is not working? I am not trying to small-talk your suggestion, but please re-think if it is really applicable.

**Comment by banjaxbanjo** [comment] 2015-04-18 23:22
Personal I think its a good idea to have it showing as @SecUpwN explained the reasons why but it wouldn't be to hard to add a preference to let user have it shown or not.

**Comment by SecUpwN** [comment] 2015-04-18 23:28
>but it wouldn't be to hard to add a preference to let user have it shown or not.

Would it be a benefit to the users having a tickbox called `Hide 'Status: OK'` in our `Interface Settings`?

**Comment by banjaxbanjo** [comment] 2015-04-18 23:33
That's true, the point of the green status icon is to indicate everything is ok and app is running so not having it there is bad idea.

**Closed** 2015-04-18 23:34 UTC
Labels: DEV_DISCUSSION, IDEA
