### ISSUE TITLE
OSD "denied position" message never disappears 

### ISSUE THREAD

**Issue by liar666** [SecUpwN/Android-IMSI-Catcher-Detector#740] opened 2016-01-04 10:35 UTC
Hi,

First of all, thanks for working to protect our privacy.

My phone is almost always in airplane mode, or at least without Wifi/GPS. Also, I often set as limited permissions as possible to newly installed applications.

When I start AIMSICD in such conditions, it shows a popup with "denied position" (see https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/739). When I finally manage to get rid of the popup and close AIMSICD, I still get an OSD notification message saying "Android-IMSI-Catcher-Detector is denied to obtain your current location". It does not disappear until I reboot my phone :[

**Comment by SecUpwN** [comment] 2016-01-08 10:26
Good evening @liar666, this Issue is in fact a dupe of #251 as well. Please monitor that one instead.

**Closed** 2016-01-08 10:26 UTC
Labels: BUG, DUPLICATE
