### ISSUE TITLE
AIMSICD freezes when denying root priv for AT command

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#432] opened 2015-05-21 13:27 UTC
1. Start AT command
2. AIMSICD freezes (I had to take out battery to stop it)
or
3. Freezes for a second and asks for root privileges again, and again, and I'm unable to stop it 

It should just go back to the previous activity.

**Comment by SecUpwN** [comment] 2015-05-22 05:18
I have tried to reproduce this, but with `SuperSU` the `AT Command Interface` just stays empty and AIMSICD neither freezes, nor does it prompt for ROOT again. Which `SU` app do you use?

**Comment by agilob** [comment] 2015-05-22 08:03
I have CarbonROM, something like SU is built-in in my ROM.

**Comment by SecUpwN** [comment] 2015-05-22 08:33
>I have CarbonROM, something like SU is built-in in my ROM.

[![SuperSU](https://lh4.ggpht.com/_kg7Qbu5kDpbjbJ2R3SvjAHKr5V0AKSsVR7nEaQznrDwFWDAD1QSrFDdcYLeqXLKLw=w300)](https://play.google.com/store/apps/details?id=eu.chainfire.supersu)

Please give [SuperSU](http://forum.xda-developers.com/showthread.php?t=1538053) a try.

**Comment by agilob** [comment] 2015-05-22 09:04
I think there's no point in testing it whether it works for you on SuperSU, it still doesn't work for me.

SU - SuperUser | SuperSU - Super Super User? oO

**Comment by SecUpwN** [comment] 2015-05-22 09:16
>I think there's no point in testing it whether it works for you on SuperSU, it still doesn't work for me.

So phone, ROM and `SU` solution do you use? You are not listed on our [Testing Devices](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Testing-Devices).

>SU - SuperUser | SuperSU - Super Super User? oO

That's something @chainfire can answer, for sure. ;-)

**Comment by E3V3A** [comment] 2015-05-31 10:49
@agilob  You need to provide more information about your device, such as exact hardware, AOS version and the exact steps needed to reproduce your error. I know its annoying to always include this info in every issue, but every issue is independent and nobody will do anything if its not clear. I'll close this issue for now, since nobody else seem to have this problem. Feel free to re-open after adding required details.

**Closed by E3V3A** 2015-05-31 10:49 UTC
Labels: BUG
