### ISSUE TITLE
"Cell ID does not exist in OpenCellID Database"

### ISSUE THREAD

**Issue by benutzer74** [SecUpwN/Android-IMSI-Catcher-Detector#349] opened 2015-03-08 23:40 UTC
After playing around with options in AIMSICD, probably download / upload local BTS Data I see the message "Cell ID does not exist in OpenCellID Database" and a yellow icon.

What exactly does this mean now? An unknown network base station? In the area they removed a base station with all antennas. I dunno if this station belonged to my mobile carrier.

By the way, my carrier offers only A5/1, but since three letter agencies have direct access to mobile carriers I think, encryption does not matter too much anyway....

**Comment by andr3jx** [comment] 2015-03-09 02:38
Hi, every BTS has a Cell ID. AIMSICD downloads a database which contains a list of all Cell IDs with their coordinates collected by OpenCellID in your area. The problem is that this database is far from complete.  "Cell ID does not exist in OpenCellID Database" means that OCID has no record for the BTS you encountered. It can mean that the OCIDs DB is incomplete or that a new BTS was activated in your area which can be an IMSI Catcher. 
For now you don't need to be concerned much about this warning. AIMSICD is still in Alpha stage and there is still much work to do. Most of carriers offer only A5/1 for GSM. 

If you just want higher security for your calls and don't need to detect IMSI Catchers:
Switch your phone to 3G-only if your area has good coverage. 3G-only mode will protect you from downgrade attacks and offers much higher security in comparison to 2G.

**Comment by SecUpwN** [comment] 2015-03-13 12:22
Hey @andr3jx, thanks for having the courage to explain this Issue properly. I knew this would come up. We specifically released our App with this "bug" to see how many people would actually notice and maybe help us fix this. @benutzer74 one solution for this is to collect data of the cell towers and upload them to the OCID database. But please be aware that this might reveal where you live. Help us fix this, please.

**Comment by E3V3A** [comment] 2015-03-23 00:32
As @andr3jx said: 
> For now you don't need to be concerned much about this warning. AIMSICD is still in Alpha stage and there is still much work to do. 

Call your network provider and ask them to upload their true BTS GPS positions to OCID and get their asses encrypted with A5/3. 

So I'm closing this issue.

**Comment by SecUpwN** [comment] 2015-03-23 05:13
>The problem is that this database is far from complete.

Don't get me wrong on this, but I feel that I have to re-open this as long as our App has not been fixed to avoid this error message. Many people have come up to me via E-Mail and asked "Hey, have I been attacked or what is this?". I expect that the above answer given will just smash a piece of wood onto the forehead of our users. Since I see that #71 is closely related, I would like to call in @hannosch to help us adding #71 as a **second** CID check via Mozilla Location Service which shall launch after our App noticed that the CID is not on the OCID database. Of course this will not totally prevent this error message, but I expect it to be appearing far less. Does that make sense to you, @He3556?

**Comment by E3V3A** [comment] 2015-03-23 14:31
Good idea @SecUpwN, let's just upload all false base stations to ensure nobody will ever detect anything again. It's all green and happy!

**Comment by SecUpwN** [comment] 2015-03-24 07:50
>Call your network provider and ask them to upload their true BTS GPS positions to OCID and get their asses encrypted with A5/3. 

>Good idea @SecUpwN, let's just upload all false base stations to ensure nobody will ever detect anything again. It's all green and happy!

Not productive for our work here, @E3V3A. I would like you to show a little more respect. Thank you.

**Comment by darkerego** [comment] 2015-04-01 23:46
I noticed that this bug is only prevalent (in my case) in the latest pre-release, 0.1.35 alpha. When I switched back to 0.1.25 alpha-b15, the issue was resolved. I did try taking lots of measurements from different locations around the area and uploading them to OpenCellID, but after a week of having the warning I went back to 0.1.25. I am on AT&T 3G, by the way. I have 2G completely disabled.

**Comment by He3556** [comment] 2015-04-02 13:46
The problem is that we can't guarantee a full and current list of Cell IDs in your area. (from the OCID download). Because of this unexpected fact, we need to change the concept of this detection. 
It looks like we can not detect it when the catcher was present at the first scan (after installing the app).

**Comment by E3V3A** [comment] 2015-06-01 13:59
Can we close this? @SecUpwN @He3556

**Comment by SecUpwN** [comment] 2015-06-04 04:27
>Can we close this?

@E3V3A, would like to, but how are we going to handle the following question?

>Because of this unexpected fact, we need to change the concept of this detection.

**Comment by E3V3A** [comment] 2015-06-04 10:10
I have no idea what that means. Perhaps @He3556 can explain?

**Comment by He3556** [comment] 2015-06-04 11:48
We need to collect the CellID's in the area by ourselves and than check for changes (new IDs) in the future. 
We can close this...

**Comment by SecUpwN** [comment] 2015-06-04 12:31
>We need to collect the CellID's in the area by ourselves and then check for changes (new IDs) in the future.

To clarify: As long as the CIDs are not uploaded to the OCID DB, people will inevitably receive this error, running around and trying to find a "more secure service area". Since I am the one receiving all the log files lately, I often get the question about this Issue listed here. We really should combine OCID with some other proven service, thinking of #446 (and of course #71) to remedy this situation. **CLOSED.**

**Closed by SecUpwN** 2015-06-04 12:31 UTC
Labels: BUG

**Comment by ehem** [comment] 2015-07-13 02:14
I'm wondering if this should be rated as a shortcoming/weakness of the OpenCellID database.  They *will* inevitably end up with at least *some* malicious cells in their database due to either accidents or malice.  As such the DB needs to have some method for cells to be marked about how confident the submitter is about the cell being kosher or not.  Knowledge of where malicious cells are is quite valuable since it allows people to find them and see examples how malicious cell behavior differs from kosher cell behavior.

I'm unsure of what my current situation is.  I doubt I'm the target of law enforcement or other entity, but AIMSICD is reporting unknown cells.  I suspect they're merely missing from OpenCellID's DB, but I don't consider myself well qualified to evaluate the data.

**Comment by SecUpwN** [comment] 2015-07-13 02:32
>I suspect they're merely missing from OpenCellID's DB

Right. You need to capture the data and upload it using AIMSICD or another app uplodaing to OCID.

**Comment by DJaeger** [comment] 2015-07-15 08:52
To track Cells you can use this one (really easy to use, but closed source):
http://zamojski.info/Features,Tower-Collector.html

**Comment by SecUpwN** [comment] 2015-07-15 14:14
Thanks for mentioning this app, @DJaeger. I just invited @zamojski to our project. Cheers!

**Comment by zamojski** [comment] 2015-07-16 14:56
Thanks for mentioning my app. Tower Collector simply collects current cell and performs very basic validation checks on retrieved cell ID. As far as I know there is no option to check if the cell is real or not, at least through Android API. Regarding OCID, they have some data filtering applied but in general you can't fully rely on data to check if the cell exists in reality or not. That's my opinion. However checking in multiple databases can give you more confidence.

**Comment by ehem** [comment] 2015-07-19 02:00
Isn't the "Upload BTS Data" ("upload_bts") supposed to implement uploading tower data? Is this functionality currently working? (this would explain observations)

**Comment by SecUpwN** [comment] 2015-07-19 20:47
>Is this functionality currently working?

@E3V3A and @He3556, would you please add some clarification on this question here (without freaking out because it is even being asked again) before I **LOCK** this Issue? As far as I know, the upload procedure currently works but of course it is not sufficient because our app stays at status yellow most of the time. What was it that we're doing to improve this behavior, making our app really stay at green when the CID does not exist in the database but multiple things have been checked?

**Comment by E3V3A** [comment] 2015-07-19 20:52
The icon **should stay yellow** since there is no way to verify anything about an unknown cell. Trying to do something else would be very counter productive. (LIke asking user to accept unknown cell.)  So until mobile service providers can provide exact BTS locations and secure A5/3, it should do exactly this.

**Comment by banjaxbanjo** [comment] 2015-07-19 20:57
This status can easily be set back to green when the cell not in ocid event is logged but if we connect to this cell again leaving it green status would probably be bad since we no nothing about this bts and having a minor yellow warning gives some caution to user to be on alert. 

Should there be an icon for connected to know cell or is green covering this.

**Comment by E3V3A** [comment] 2015-07-19 21:05
Exactly, it revert to green, once your device reconnect to known cell. Just tested today.
