### ISSUE TITLE
Silent SMS and Database viewer

### ISSUE THREAD

**Issue by guardtheveldt** [SecUpwN/Android-IMSI-Catcher-Detector#252] opened 2015-01-01 18:58 UTC
Hey guys!
Awesome work with AIMSICD. I am thrilled that there are people out there such as yourselves to help us lay people guard privacy! That being said I did notice an issue on my Galaxy S4 running on Verizon. Anytime I receive an ordinary SMS I am alerted that it is a silent SMS or Type-0. I was gonna go through the database to send you guys a report, but anytime I try to pull it for silent SMS the app crashes on me :( anything i can do to help out with that issue without a sending a crash report?

**Comment by SecUpwN** [comment] 2015-01-01 19:09
Hi there @guardtheveldt, thanks for the warm words! Actually, our Silent/Stealth SMS Detection is still not implemented properly, thus I see this to be an Issue related to #69. Please post a link to your logcat on [PIE BIN](https://defuse.ca/pastebin.htm) there and make sure to remove sensitive data first.

**Comment by E3V3A** [comment] 2015-01-01 23:08
@guardtheveldt  Hi There and Welcometo GitHub! Don't get discouraged about us closing this issue, there is a secondary problem, which came to mind when seeing this. I think your Verizon network is using CDMA and believe that SMS are handled slightly different there. Since we are mostly developing on European devices your bug report is very important to us. Please see our [bug report](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues) instructions how to make a dump of the logcat, from command line. Or if you're not familiar with command line, download and install the *catLog* app.

**Comment by E3V3A** [comment] 2015-01-01 23:29
BTW. @guardtheveldt Let me understand. What did you do to pull silent SMS DB? Did you try to export DB? or what? 

@SecUpwN I think we should re-open this if the problem is in the DB viewer.

**Comment by SecUpwN** [comment] 2015-01-01 23:49
>I think we should re-open this if the problem is in the DB viewer.

Of course, but how can we even tell, @E3V3A? The core feature is buggy.

* Error: `Anytime I receive an ordinary SMS I am alerted that it is a silent SMS or 0Type.`
* BUG: `...but anytime I try to pull it for silent SMS the app crashes on me...`

I cannot confirm even one of these things, since `Load Data` is not crashing on the current version of the App. So please clarify what exactly you did, @guardtheveldt. Thank you for your patience.

**Comment by E3V3A** [comment] 2015-01-02 00:03
Maybe he tried to export the DB?

**Comment by SecUpwN** [comment] 2015-01-07 08:12
@guardtheveldt, please reply with more information within **one day**. Respect our 7-day-rule!

**Closed** 2015-01-08 07:38 UTC
Labels: BUG, DUPLICATE
