### ISSUE TITLE
AIMSICD does not quit

### ISSUE THREAD

**Issue by lop1** [SecUpwN/Android-IMSI-Catcher-Detector#519] opened 2015-07-02 19:00 UTC
seems impossible to quit AIMSICD 0.1.30 alpha b8 without rebooting the phone.

**Comment by SecUpwN** [comment] 2015-07-02 19:02
Dupe of #498. Please sift through our existing Issues in the future before filing a fresh one. Thanks.

**Closed** 2015-07-02 19:02 UTC
Labels: DUPLICATE

**Comment by lop1** [comment] 2015-07-02 19:05
sorry, I supposed it was fixed because it was working in the 0.1.30 alpha B00.

**Comment by DJaeger** [comment] 2015-07-02 22:30
@lop1: It seemed to be fixed for some but not all.
As no one can give me a logcat to see what is causing the crash I can't look into it.
But I think the crash that you now have is the newly introduced of #516 which is already filed at #325.
