### ISSUE TITLE
Support of dual SIM phones

### ISSUE THREAD

**Issue by Cellino** [SecUpwN/Android-IMSI-Catcher-Detector#689] opened 2015-12-18 08:58 UTC
On the dialog phone/SIM details is always shown one SIM card. Please pay attention to full dual SIM phones, I have such a thing. There are 2 full available SIM cards, in my case with two different providers. It is possible to switch data connection from one to the other SIM card and back again, but you can connect only with one SIM card at the time. I don't know whether and how you want to support this point and e.g. show both SIM card informations on the phone/SIM details tab/dialog.

**Comment by larsgrefer** [comment] 2015-12-18 09:28
@Cellino duplicate of #504. Please add your request there

**Closed by larsgrefer** 2015-12-18 09:28 UTC
