### ISSUE TITLE
Counter Measure: Switching IMEI

### ISSUE THREAD

**Issue by He3556** [SecUpwN/Android-IMSI-Catcher-Detector#94] opened 2014-07-30 11:40 UTC
**Structure of the IMEI before 2003**
![imei_digits](https://cloud.githubusercontent.com/assets/2507905/3748500/c9bdc136-17dd-11e4-99aa-2cf32f2905dd.jpg)
(TAC - Type of device; FAC - Country where it was build)

**Structure of the IMEI after 2004**
![github_imei](https://cloud.githubusercontent.com/assets/2507905/3814820/aab61366-1cbe-11e4-9bf8-dfea650089c2.jpg)

The IMEI can be stored in the EIR (Equipment ID Register) which can be found in the core network of the provider. The number is transfered when the mobile phone gets switched on. The EIR has an IMSI blacklist of stolen phones, so they can be blocked. Blacklists needs to be exchanged (globally) – this is only working in some countries (in Europe it is the CEIR – Central Equipment Identity Register). The identity of the user of a blacklisted phone can be determined through the SIM card (IMSI) he/she is using when switching on the stolen phone.

I was looking for a **database to download with TAC and SNR** – and only found this:
(numberingplans)[http://www.numberingplans.com/index.php?page=databases]
**Next publications are planned for the week of 18 August 2014.**

The **Check Digit** is not part of the digits transmitted. 
The Check Digit shall be calculated according to Luhn formula (ISO/IEC 7812).  (see Wikipedia)[http://en.wikipedia.org/wiki/Luhn_algorithm]
See GSM 02.16 / 3GPP 22.016 and (ts_123003v100500p.pdf)[http://www.etsi.org/deliver/etsi_ts/123000_123099/123003/10.05.00_60/ts_123003v100500p.pdf]
But there are more papers out there from ETSI and 3gpp

Overviev of the **Computation of the Check Digit** from the IMEI proceeds as follows: 
Step 1: Double the values of the odd labelled digits D1, D3, D5 ... D13 of the IMEI. 
Step 2: Add together the individual digits of all the seven numbers obtained in Step 1, and then add this sum to the sum of all the even labelled digits D2, D4, D6 ... D14 of the IMEI. 
Step 3: If the number obtained in Step 2 ends in 0, then set CD to be 0. If the number obtained in Step 2 does not end in 0, then set CD to be that number subtracted from the next higher number which does end in 0.

'EXAMPLE 

IMEI (14 most significant digits): 

TAC SNR 
 D14 D13 D12 D11 D10 D9 D8 D7 D6 D5 D4 D3 D2 D1 
 2 6 0 5 3 1 7 9 3 1 1 3 8 3 ETSI 

*3GPP TS 23.003 version 11.8.0 Release 11 75 ETSI TS 123 003 V11.8.0 (2014-03)*

Step 1: 
 2 6 0 5 3 1 7 9 3 1 1 3 8 3 
 x2 x2 x2 x2 x2 x2 x2 
 12 10 2 18 2 6 6 

Step 2: 
 2 + 1 + 2 + 0 + 1 + 0 + 3 + 2 + 7 + 1 + 8 + 3 + 2 + 1 + 6 + 8 + 6 = 53 
Step 3: 
 CD = 60 - 53 = 7'

**Implementation in JAVA** – (here!!!)[https://github.com/nishan/luhn_java/blob/master/src/org/luhn/Luhn.java]

**Additional Infos:**
- On the CDMA Standard it is called MEID and is HEX
- IMSI analysis you can use (this)
[https://www.numberingplans.com/?page=analysis&sub=imeinr]

**Comment by SecUpwN** [comment] 2015-03-17 09:07
@DizzyDen, thanks for your commitment! We'd like to thrive forward with our project and would love you to work on an implementation of this using pull requests of on our project. We're looking forward to it!

**Comment by andr3jx** [comment] 2015-03-17 13:43
I don't think DizzyDen's work is useful for the project. The problem is that changing the IMEI for the OS doesn't impact the IMEI seen by the baseband.

**Comment by SecUpwN** [comment] 2015-03-17 16:51
>The problem is that changing the IMEI for the OS doesn't impact the IMEI seen by the baseband.

Where would we have to change it then? Why should this be a "completely impossible" task?

**Comment by andr3jx** [comment] 2015-03-17 18:20
Most phones make changing IMEI very hard. It is very device specific and the work is not worth it. IMEI is not relevant for detecting IMSI catchers. The only valid use I see is to change IMEI to make detection of SIM changes harder.

**Comment by doidays** [comment] 2015-03-17 18:29
surely yes, it might hv to deploy a new system to make easy for it.

**Comment by E3V3A** [comment] 2015-05-08 23:32
There are instructions available for a whole range of models, even older Qualcomm based phones, so this can definitely be at least partially implemented. With the better understanding of the QMI and QCRIL interfaces, we should eventually find a way to re-write IMEI for any device. Now doing this is highly controversial, and evenm illegal in some countries, so I don't think this will be implemented anytime soon. Thus closing this until further notice.

**Closed by E3V3A** 2015-05-08 23:32 UTC
Labels: C_MEASURES, DEV_DISCUSSION, REMEMBER_THIS
