### ISSUE TITLE
Database Viewer: Imported OCID Data seems empty

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#434] opened 2015-05-22 05:38 UTC
@agilob did discover during #429 that imported OCID data is missing in the Database Viewer:

>I'm not sure if importing OCID data works, after **import is successful** there is nothing listed in the database viewer. There is no problem gathering data from near cells and storing them in the DB, so I'm not sure whose fault is this.

This Issue needs further investigation. I guess its something simple since it was displayed before.

**Comment by E3V3A** [comment] 2015-05-31 08:52
Just tested **v0.1.28-alpha-b03**  and I can confirm this issue. I don't even get an import successful message. I have no idea if the download worked or failed for some other reason. Nothing shown in `Impoertd OCID Data`.

**Comment by gusfl** [comment] 2015-05-31 09:31
I confirm this issue too on *v0.1.28-apha-b00*. It's a pretty serious bug, because it cause the app to switch in MEDIUM threat level : "Cell ID does not exist in OpenCellID".

**Comment by E3V3A** [comment] 2015-06-08 00:29
This is a very annoying bug, that was crept into some fairly recent code cleanups. @banjaxbanjo or @ziem can you please have a look to see what's causing this? (I think it may be an index issue...)

**Comment by marvinmarnold** [comment] 2015-06-08 04:25
Problem was that updateOpenCellID was loading the wrong filename. Fixed in pull request #454.

Some additional notes, mostly to self, below.Most of you prob already understand the flow of things but this comment might help for anybody new as it was not clear for me. To test this error:
1) Click on settings in sidebar. Click on Request OCID API Key -> OK. API keys are not automatically requested otherwise.
2) Click on "Download BTS Data" in sidebar. This ultimately calls RequestTask in the background and writes data to CSV. That CSV only gets loaded to DB on AIMSICDDbAdapter#updateOpenCellID which is called on post execute.

**Comment by E3V3A** [comment] 2015-06-08 14:32
Thanks again @marvinmarnold for fixing this issue!

**Closed by E3V3A** 2015-06-08 14:32 UTC
Labels: BUG, URGENT

**Comment by jawz101** [comment] 2015-12-29 17:38
I don't know how this is fixed.  I'm on cm13 on a Nexus 5.  I never see anything in that Database Viewer: Imported OCID Data screen

**Comment by SecUpwN** [comment] 2015-12-29 23:06
@jawz101, please press `Download BTS Data` in the `Navigation Drawer` and tell me here if it worked.

**Comment by jawz101** [comment] 2015-12-30 21:39
Thanks.  I did and it didn't show anything in the table viewer.  The download process takes about a second.  The debugging log shown below led me to look at the csv file and it did save a file 112 bytes in size with just the top row it looks like (ie. table column headers).

Could it be my location?  I'm in a city that is fairly large and I do see tower spots on the opencellid website for my area on their map view.

I/a       (21151): Checking for db first install this will throw an error on install and is normal
D/AppAIMSICD(21151): BaseTask addTask activity:com.SecUpwN.AIMSICD.AIMSICD
I/x       (21151): DBE_DOWNLOAD_REQUEST write to: /storage/emulated/0/Android/data/com.SecUpwN.AIMSICD/files/OpenCellID/opencellid.csv
D/x       (21151): doInBackground DBE_DOWNLOAD_REQUEST total: 112
I/a       (21151): UpdateOpenCellID: OCID CSV size (lines): 1
D/a       (21151): PopulateDBeImport(): inserted 1 cells.
D/a       (21151): CheckDBe() Attempting to delete bad import data from DBe_import table...
I/a       (21151): CheckDBe() Deleted BTS entries from DBe_import table with bad LAC/CID...

**Comment by jawz101** [comment] 2015-12-30 22:29
looks like prior to it the log has this stuff:
OCID BBOX is set to: <latmin>,<lonmin>,<latmax>,<lonmax> with radius 2km
l/n OCID MCC is set to: <mcc>
l/n OCID MNC is set to: <mnc>

*redacted my actual coordinates and MCC/MNC values with the variable names.

Hmmm.  I tried opening it in my browser to see what I get .. even extended the distance out about 30 miles and still get 0 returning.

opencellid.org/cell/getInArea?key=(my API key)&BBOX=(latmin,lonmin,latmax,lonmax)&mcc=(mcc)&mnc=(mnc)&lac=(mylac)&format=json

I played around and I added &radio=GSM (for the heck of it), took away the mcc, mnc & lac and finally got data back - 21kilobytes this time
it wouldn't return anything until I took the mnc mobile network code out

I use one of those no contract MVNO's that piggybacks off of AT&T which may explain it.

**Comment by agilob** [comment] 2015-12-31 09:22
> it wouldn't return anything until I took the mnc mobile network code out

MNC is network code of your provided, if nothing was returned that means OCID doesn't have data for your current MNC and this is fine. Removing MNC is asking for (minor) problems. You as ATT customer don't want to check if there is TMobile BTS, because unless you're on roaming, you won't connect to it. You downloaded 21kb of data that will never be used for good but can only cause false positive alert. If you are on roaming from TMobile, you will get different MNC and **then** you can redownload OCID data.

**Comment by jawz101** [comment] 2016-01-01 03:05
Well if I'm on an MVNO which I know piggyback's off of AT&T's network could I not manually specify AT&T's MNC as my MVNO uses the same towers as AT&T?
