### ISSUE TITLE
Better standard TAG for logcat events

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#324] opened 2015-02-16 04:14 UTC
We need better and more clear Log TAG's when adding debug output code like this `Log.x(TAG, "...")`. I suggest we standardize it to: 
 1. For ***Log.d/v*** use:  `Log.x(TAG, mTAG + "your info text")`
 2. For ***Log.i***   use:  `Log.i(TAG, "your info text")`                    
 3. For **alerts**  use:  `Log.e(TAG, "ALERT! your info text")`                 
 4. For **errors**  use:  `Log.e(TAG, "ERROR! your info text")`                 

where: 
```
TAG="AIMSICD" 
mTAG="<module/filename>: "
```

**Why?** So that we can easily spot from logcat things that are directly related to AIMSICD and what files we can look for bugs...

**Comment by tobykurien** [comment] 2015-03-05 14:53
I don't understand the need for this? You can just set the mTAG as the log tag, there's no need for the log tag to be "AIMSICD". If you're thinking that we could use "AIMSICD" as a way to see all logs from our app, the better way is to filter by package/app name. ```logcat V``` for example will include the app name in it: ```D/AIMSICD ( 8052): CellTracker: neighbouringCellInfo empty: trying 1```

**Comment by E3V3A** [comment] 2015-03-05 16:26
Huh, have I missed something? Form my experience, the TAG we use is often hard-coded in the beginning of each file, and non-standard. Thus logcat shows all sorts of stuff and often not marked with AIMSICD. Second reason is that, when you separate the TAG, you'll get the PID immediately after the "AIMSICD" string which is also what I wanted as a standard, since it is then much easier to spot in any logcat version. I tried that filtering before, but then we missed stuff... Ok, let me have another look at this.

**Comment by marvinmarnold** [comment] 2015-06-10 01:25
Like @tobykurien, I also don't understand the need for TAG. Android Studio automatically filters by package and I'm assuming its fairly easy to do the same in Eclipse or whatever other IDE as well. What I've seen most commonly is to make TAG the class name with mTAG/etc up to the individual. @E3V3A  I'm not sure what you mean by the PID following the TAG otherwise.

**Comment by E3V3A** [comment] 2015-06-10 03:45
I don't use AS or Eclipse for debugging. I'm using command-line logcat, which is where these problems occur, and making debugging and filing proper bug reports a PITA. I'm using verbose logs to get all info from all buffers and having BB debug info set to high, I get megabytes of logcats in a matter of minutes, without possibility of proper filtering, it is a real PITA.

**Comment by E3V3A** [comment] 2015-06-25 13:19
Fix log TAGs in [RilExecutor.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/rilexecutor/RilExecutor.java) and [SamsungMulticlientRilExecutor.java](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/rilexecutor/SamsungMulticlientRilExecutor.java) with the corresponding equivalents of something like this:

```java
protected static final String TAG = "AIMSICD";
protected static final String mTAG = "RilExecutor "; //MultiRil
```
with:
```
...
Log.e(TAG, mTAG + " Blah blah problem:", e);
```

**Comment by SecUpwN** [comment] 2015-06-25 18:11
@E3V3A I've just merged the PR above. Is this fixed now?

**Comment by DJaeger** [comment] 2015-06-25 19:20
Looks like expected.
Could see the new TAGs for a timeout error of RilExecuter.
As I can not reproduce the error, I only mention it in this context, but will not file an issue.

**Comment by E3V3A** [comment] 2015-06-26 00:10
@DJaeger Hmm I wonder if this is the problem with #505 ? (Also see my comment in the commit PR.)

**Closed** 2015-06-26 11:55 UTC
Labels: BUG, ENHANCEMENT, PRIORITY
