### ISSUE TITLE
GUI force close/crash services keep running

### ISSUE THREAD

**Issue by gorillap** [SecUpwN/Android-IMSI-Catcher-Detector#718] opened 2015-12-29 11:43 UTC
Tested new 0.1.37 WIP Alpha version and immediately upon opening, GUI force closed, but still received messages that services were starting. Icon continued to show on notification bar.
0.1.36 WIP Alpha is running fine.

LG Google Nexus 5X 16GB
Custom Android 6.0.1 (Rooted)

**Comment by cwmke** [comment] 2015-12-29 14:41
Same issue on a Nexus 6p.  Here are some of the logs
````
PackageManager.DexOptimizer(5055): Running dexopt (dex2oat) on: /data/app/vmdl1105883660.tmp/base.apk pkg=com.SecUpwN.AIMSICD isa=arm64 vmSafeMode=false debuggable=false oatDir = /data/app/vmdl1105883660.tmp/oat bootComplete=true

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission android.permission.ACCESS_SUPERUSER in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission android.permission.ACCESS_COARSE_UPDATES in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Not granting permission android.permission.INTERACT_ACROSS_USERS_FULL to package com.SecUpwN.AIMSICD (protectionLevel=258 flags=0x38083e44)

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission android.phone.receiveDetailedCallState in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission com.android.permission.HANDOVER_STATUS in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission com.sec.android.app.controlpanel.permission.PRIVATE in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission com.sec.android.app.factorymode.permission.KEYSTRING in package com.SecUpwN.AIMSICD

12-29 08:19:05.269 W/PackageManager(5055): Unknown permission com.sec.android.app.cm.permission.PERMISSION_MANAGEMENT in package com.SecUpwN.AIMSICDUnknown

12-29 08:19:05.270 W/PackageManager(5055):  permission com.sec.android.app.phoneutil.permission.KEYSTRING in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.android.app.servicemodeapp.permission.KEYSTRING in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.android.phone.permission.DATA_ROAMING_SETTINGS_ENHANCED in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.android.phone.permission.READ_CALL_SETTINGS in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.android.phone.permission.WRITE_CALL_SETTINGS in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.factory.permission.KEYSTRING in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission com.sec.modem.settings.permission.KEYSTRING in package com.SecUpwN.AIMSICD

12-29 08:19:05.270 W/PackageManager(5055): Unknown permission org.simalliance.openmobileapi.SMARTCARD in package com.SecUpwN.AIMSICD

12-29 08:19:05.487 D/BluetoothMapAppObserver(7157): The installed package is: com.SecUpwN.AIMSICD

12-29 08:19:05.935 V/ApkTrack(14302): Received APP_ADDED (com.SecUpwN.AIMSICD). The activity will be informed.

12-29 08:19:30.239 I/ActivityManager(5055): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.SecUpwN.AIMSICD cmp=com.SecUpwN.AIMSICD/.AIMSICD} from uid 10096 on display 0

12-29 08:19:30.301 I/ActivityManager(5055): Start proc 16454:com.SecUpwN.AIMSICD/u0a146 for activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:19:30.356 W/System  (16454): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:19:30.386 V/FolderObserver(14388): Received inotify event 100 at /Android/data/com.SecUpwN.AIMSICD

12-29 08:19:30.386 V/PostScanTask(14388): Calling Rest API at https://127.0.0.1:8384/rest/db/scan?folder=androidbk&sub=%2FAndroid%2Fdata%2Fcom.SecUpwN.AIMSICD

12-29 08:19:30.441 D/AppAIMSICD(16454): BaseTask attach:com.SecUpwN.AIMSICD.AIMSICD

12-29 08:19:30.710 I/ActivityManager(5055): Displayed com.SecUpwN.AIMSICD/.AIMSICD: +428ms

12-29 08:19:55.442 E/SQLiteLog(16454): (14) os_unix.c:31278: (2) open(/data/user/0/com.SecUpwN.AIMSICD/databases/aimsicd.db) - 

12-29 08:19:55.461 E/SQLiteDatabase(16454): Failed to open database '/data/user/0/com.SecUpwN.AIMSICD/databases/aimsicd.db'.

12-29 08:19:55.461 E/SQLiteDatabase(16454): 	at com.SecUpwN.AIMSICD.a.a.s(AIMSICDDbAdapter.java:221)

12-29 08:19:55.461 E/SQLiteDatabase(16454): 	at com.SecUpwN.AIMSICD.a.a.a(AIMSICDDbAdapter.java:193)

12-29 08:19:55.461 E/SQLiteDatabase(16454): 	at com.SecUpwN.AIMSICD.a.a.<init>(AIMSICDDbAdapter.java:156)

12-29 08:19:55.461 E/SQLiteDatabase(16454): 	at com.SecUpwN.AIMSICD.service.s.<init>(SignalStrengthTracker.java:103)

12-29 08:19:55.461 E/SQLiteDatabase(16454): 	at com.SecUpwN.AIMSICD.service.AimsicdService.onCreate(AimsicdService.java:93)

12-29 08:19:55.462 E/a       (16454): 	at com.SecUpwN.AIMSICD.a.a.s(AIMSICDDbAdapter.java:221)

12-29 08:19:55.462 E/a       (16454): 	at com.SecUpwN.AIMSICD.a.a.a(AIMSICDDbAdapter.java:193)

12-29 08:19:55.462 E/a       (16454): 	at com.SecUpwN.AIMSICD.a.a.<init>(AIMSICDDbAdapter.java:156)

12-29 08:19:55.462 E/a       (16454): 	at com.SecUpwN.AIMSICD.service.s.<init>(SignalStrengthTracker.java:103)

12-29 08:19:55.462 E/a       (16454): 	at com.SecUpwN.AIMSICD.service.AimsicdService.onCreate(AimsicdService.java:93)

12-29 08:19:55.647 I/AimsicdService(16454): Service launched successfully.

12-29 08:19:55.777 E/AndroidRuntime(16454): Process: com.SecUpwN.AIMSICD, PID: 16454

12-29 08:19:55.777 E/AndroidRuntime(16454): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:19:55.777 E/AndroidRuntime(16454): 	at com.SecUpwN.AIMSICD.service.AimsicdService.k(AimsicdService.java:242)

12-29 08:19:55.777 E/AndroidRuntime(16454): 	at com.SecUpwN.AIMSICD.f.onServiceConnected(AIMSICD.java:489)

12-29 08:19:55.792 W/ActivityManager(5055):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:19:56.321 W/ActivityManager(5055): Activity pause timeout for ActivityRecord{5f2d657 u0 com.SecUpwN.AIMSICD/.AIMSICD t418 f}

12-29 08:19:57.662 I/WindowState(5055): WIN DEATH: Window{2436d99 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}

12-29 08:19:57.673 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16454) has died

12-29 08:19:57.674 W/ActivityManager(5055): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000m

12-29 08:19:57.723 W/NotificationService(5055): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@8d26e in package com.SecUpwN.AIMSICD

12-29 08:19:57.724 W/NotificationService(5055): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@2f34d0f in package com.SecUpwN.AIMSICD

12-29 08:19:58.537 I/ActivityManager(5055): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.SecUpwN.AIMSICD cmp=com.SecUpwN.AIMSICD/.AIMSICD} from uid 10096 on display 0

12-29 08:19:58.603 I/ActivityManager(5055): Start proc 16517:com.SecUpwN.AIMSICD/u0a146 for activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:19:58.641 W/System  (16517): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:19:58.700 D/AppAIMSICD(16517): BaseTask attach:com.SecUpwN.AIMSICD.AIMSICD

12-29 08:19:58.801 I/AimsicdService(16517): Service launched successfully.

12-29 08:19:58.965 E/AndroidRuntime(16517): Process: com.SecUpwN.AIMSICD, PID: 16517

12-29 08:19:58.965 E/AndroidRuntime(16517): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:19:58.965 E/AndroidRuntime(16517): 	at com.SecUpwN.AIMSICD.service.AimsicdService.k(AimsicdService.java:242)

12-29 08:19:58.965 E/AndroidRuntime(16517): 	at com.SecUpwN.AIMSICD.f.onServiceConnected(AIMSICD.java:489)
12-29 08:19:58.966 W/ActivityManager(5055):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:19:59.493 W/ActivityManager(5055): Activity pause timeout for ActivityRecord{bac919c u0 com.SecUpwN.AIMSICD/.AIMSICD t419 f}

12-29 08:20:00.477 I/WindowState(5055): WIN DEATH: Window{46b5664 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}

12-29 08:20:00.488 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16517) has died

12-29 08:20:00.488 W/ActivityManager(5055): Service crashed 2 times, stopping: ServiceRecord{a9c6f0d u0 com.SecUpwN.AIMSICD/.service.AimsicdService}

12-29 08:20:00.913 W/NotificationService(5055): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@914f073 in package com.SecUpwN.AIMSICD

12-29 08:20:00.914 W/NotificationService(5055): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@b1f9b30 in package com.SecUpwN.AIMSICD

12-29 08:20:36.478 I/ActivityManager(5055): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.SecUpwN.AIMSICD cmp=com.SecUpwN.AIMSICD/.AIMSICD} from uid 10096 on display 0

12-29 08:20:36.565 I/ActivityManager(5055): Start proc 16756:com.SecUpwN.AIMSICD/u0a146 for activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:20:36.627 W/System  (16756): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:20:36.685 D/AppAIMSICD(16756): BaseTask attach:com.SecUpwN.AIMSICD.AIMSICD

12-29 08:20:36.802 I/AimsicdService(16756): Service launched successfully.

12-29 08:20:36.985 E/AndroidRuntime(16756): Process: com.SecUpwN.AIMSICD, PID: 16756

12-29 08:20:36.985 E/AndroidRuntime(16756): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:20:36.985 E/AndroidRuntime(16756): 	at com.SecUpwN.AIMSICD.service.AimsicdService.k(AimsicdService.java:242)

12-29 08:20:36.985 E/AndroidRuntime(16756): 	at com.SecUpwN.AIMSICD.f.onServiceConnected(AIMSICD.java:489)

12-29 08:20:36.988 W/ActivityManager(5055):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:20:37.296 I/WindowManager(5055): Screenshot max retries 4 of Token{defe00e ActivityRecord{ce5e609 u0 com.SecUpwN.AIMSICD/.AIMSICD t421 f}} appWin=Window{6c8d196 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD} drawState=1

12-29 08:20:37.799 W/ActivityManager(5055): Activity pause timeout for ActivityRecord{ce5e609 u0 com.SecUpwN.AIMSICD/.AIMSICD t421 f}

12-29 08:20:38.519 W/InputDispatcher(5055): channel '6c8d196 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

12-29 08:20:38.520 I/WindowState(5055): WIN DEATH: Window{6c8d196 u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}

12-29 08:20:38.520 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16756) has died

12-29 08:20:38.520 W/ActivityManager(5055): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms

12-29 08:20:38.523 E/InputDispatcher(5055): channel '6c8d196 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)' ~ Channel is unrecoverably broken and will be disposed!

12-29 08:20:38.524 W/InputDispatcher(5055): Attempted to unregister already unregistered input channel '6c8d196 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)'

12-29 08:20:38.946 W/NotificationService(5055): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@dd4f6f7 in package com.SecUpwN.AIMSICD

12-29 08:20:38.947 W/NotificationService(5055): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@f69964 in package com.SecUpwN.AIMSICD

12-29 08:20:39.535 I/ActivityManager(5055): Start proc 16787:com.SecUpwN.AIMSICD/u0a146 for service com.SecUpwN.AIMSICD/.service.AimsicdService

12-29 08:20:39.577 W/System  (16787): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:20:39.772 I/AimsicdService(16787): Service launched successfully.

12-29 08:20:45.165 V/NlpLocationProvider(6835): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10146 com.SecUpwN.AIMSICD}

12-29 08:20:45.207 E/AndroidRuntime(16787): Process: com.SecUpwN.AIMSICD, PID: 16787

12-29 08:20:45.207 E/AndroidRuntime(16787): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:20:45.207 E/AndroidRuntime(16787): 	at com.SecUpwN.AIMSICD.service.AimsicdService.f(AimsicdService.java:54)

12-29 08:20:45.207 E/AndroidRuntime(16787): 	at com.SecUpwN.AIMSICD.service.i.onProviderDisabled(AimsicdService.java:284)

12-29 08:20:45.207 E/AndroidRuntime(16787): 	at com.SecUpwN.AIMSICD.service.r.onProviderDisabled(LocationTracker.java:173)

12-29 08:20:49.439 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16787) has died

12-29 08:20:49.439 W/ActivityManager(5055): Service crashed 2 times, stopping: ServiceRecord{71a68be u0 com.SecUpwN.AIMSICD/.service.AimsicdService}

12-29 08:20:51.336 D/StatusBar(6353): Clicked on content of 0|com.SecUpwN.AIMSICD|1|null|10146

12-29 08:20:51.342 I/ActivityManager(5055): START u0 {flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD (has extras)} from uid 10146 on display 0

12-29 08:20:51.345 W/ActivityManager(5055): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x20000004 cmp=com.SecUpwN.AIMSICD/.AIMSICD (has extras) }

12-29 08:20:51.405 I/ActivityManager(5055): Start proc 16860:com.SecUpwN.AIMSICD/u0a146 for activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:20:51.449 W/System  (16860): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:20:51.516 D/AppAIMSICD(16860): BaseTask attach:com.SecUpwN.AIMSICD.AIMSICD

12-29 08:20:51.630 I/AimsicdService(16860): Service launched successfully.

12-29 08:20:51.800 E/AndroidRuntime(16860): Process: com.SecUpwN.AIMSICD, PID: 16860

12-29 08:20:51.800 E/AndroidRuntime(16860): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:20:51.800 E/AndroidRuntime(16860): 	at com.SecUpwN.AIMSICD.service.AimsicdService.k(AimsicdService.java:242)

12-29 08:20:51.800 E/AndroidRuntime(16860): 	at com.SecUpwN.AIMSICD.f.onServiceConnected(AIMSICD.java:489)

12-29 08:20:51.802 W/ActivityManager(5055):   Force finishing activity com.SecUpwN.AIMSICD/.AIMSICD

12-29 08:20:52.326 W/ActivityManager(5055): Activity pause timeout for ActivityRecord{aecb98d u0 com.SecUpwN.AIMSICD/.AIMSICD t422 f}

12-29 08:20:53.589 W/InputDispatcher(5055): channel '12a204a com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)' ~ Consumer closed input channel or an error occurred.  events=0x9

12-29 08:20:53.589 E/InputDispatcher(5055): channel '12a204a com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)' ~ Channel is unrecoverably broken and will be disposed!

12-29 08:20:53.590 I/WindowState(5055): WIN DEATH: Window{12a204a u0 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD}

12-29 08:20:53.590 W/InputDispatcher(5055): Attempted to unregister already unregistered input channel '12a204a com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.AIMSICD (server)'

12-29 08:20:53.596 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16860) has died

12-29 08:20:53.597 W/ActivityManager(5055): Scheduling restart of crashed service com.SecUpwN.AIMSICD/.service.AimsicdService in 1000ms

12-29 08:20:53.749 W/NotificationService(5055): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@3b0739b in package com.SecUpwN.AIMSICD

12-29 08:20:53.749 W/NotificationService(5055): Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@a3ca338 in package com.SecUpwN.AIMSICD

12-29 08:20:54.619 I/ActivityManager(5055): Start proc 16894:com.SecUpwN.AIMSICD/u0a146 for service com.SecUpwN.AIMSICD/.service.AimsicdService

12-29 08:20:54.672 W/System  (16894): ClassLoader referenced unknown path: /data/app/com.SecUpwN.AIMSICD-1/lib/arm64

12-29 08:20:54.845 I/AimsicdService(16894): Service launched successfully.

12-29 08:21:18.778 V/NlpLocationProvider(6835): onSetRequest: ProviderRequest[ON interval=+10s0ms] by WorkSource{10146 com.SecUpwN.AIMSICD}

12-29 08:21:18.818 E/AndroidRuntime(16894): Process: com.SecUpwN.AIMSICD, PID: 16894

12-29 08:21:18.818 E/AndroidRuntime(16894): 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)

12-29 08:21:18.818 E/AndroidRuntime(16894): 	at com.SecUpwN.AIMSICD.service.AimsicdService.f(AimsicdService.java:54)

12-29 08:21:18.818 E/AndroidRuntime(16894): 	at com.SecUpwN.AIMSICD.service.i.onProviderDisabled(AimsicdService.java:284)

12-29 08:21:18.818 E/AndroidRuntime(16894): 	at com.SecUpwN.AIMSICD.service.r.onProviderDisabled(LocationTracker.java:173)

12-29 08:21:20.912 I/ActivityManager(5055): Process com.SecUpwN.AIMSICD (pid 16894) has died

12-29 08:21:20.912 W/ActivityManager(5055): Service crashed 2 times, stopping: ServiceRecord{4d6e4f2 u0 com.SecUpwN.AIMSICD/.service.AimsicdService}
````

**Comment by larsgrefer** [comment] 2015-12-29 14:46
@cwmke Thanks for the stacktrace.

We should test this again with the next release, in order to get readable stacktraces

**Comment by cwmke** [comment] 2015-12-29 14:52
Sounds good.  I'll add another one after F-droid updates.

**Comment by SecUpwN** [comment] 2015-12-29 23:11
@gorillap, is this Issue possibly related or a dupe of #706?

**Comment by gorillap** [comment] 2015-12-30 19:13
I did see that and wanted to mebtion this because.
In #706, there is no mention of the GUI force-close, which had not yet been reported.
However, the services continuing to run after the GUI fc, may be the same issue.

**Comment by SecUpwN** [comment] 2015-12-30 19:37
>However, the services continuing to run after the GUI fc, may be the same issue.

@gorillap, thanks for notifying, we will handle bonth separately and see if one fixes the other. Note: We only have a handful developers and rely on contributions. Feel invited to help us find developers!

**Comment by thestinger** [comment] 2015-12-31 12:26
I think this is the same issue:

```
12-31 07:21:39.207 15002 15002 D AndroidRuntime: Shutting down VM
12-31 07:21:39.209 15002 15002 E AndroidRuntime: FATAL EXCEPTION: main
12-31 07:21:39.209 15002 15002 E AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 15002
12-31 07:21:39.209 15002 15002 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@eb98303 -- permission denied for this window type
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:319)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.service.AimsicdService.m(AimsicdService.java:270)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.service.AimsicdService.f(AimsicdService.java:54)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.service.i.onProviderDisabled(AimsicdService.java:284)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.SecUpwN.AIMSICD.service.r.onProviderDisabled(LocationTracker.java:173)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:298)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:230)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-31 07:21:39.209 15002 15002 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by SecUpwN** [comment] 2016-01-18 07:25
@gorillap, as you can see from the above closed Issue, this should be fixed. Please test the latest release.

**Comment by gorillap** [comment] 2016-01-19 04:53
Tested latest test release 0.1.38 and issue is fixed.

**Closed** 2016-01-19 12:21 UTC
Labels: BUG
