### ISSUE TITLE
BETA: AIMSICD-Installer on GooglePlay

### ISSUE THREAD

**Issue by bili123** [SecUpwN/Android-IMSI-Catcher-Detector#202] opened 2014-12-10 19:43 UTC
Hi there! I do understand the issues with Google Play and its policies but there's one problem regarding mainstream users: What's not on Play, barely exists. F-Droid ist great but even most techies don't really care about it.  I wrote dozens of articles about it and the feedback was - well, what feedback ...

So it would be great to find a way to get on Google, a simple launcher would do the job.

But even if  it's not the app itself: I don't love the idea, but just to get thinking started: What about some sort of IMSI Catcher Information App with basic information about AIMSICD, IMSI Catcher, background articles (wikipedia) and all above a launcher or link. Just a first brainstormed idea ...

**Comment by E3V3A** [comment] 2015-01-21 00:18
Are we still considering this? Perhaps we can close this...for now?

**Comment by SecUpwN** [comment] 2015-02-27 16:40
Since our App has been published on GooglePlay without asking us beforehand, I am reopening this and will open an official GooglePlay Account for our App after it has been removed by the other uploader. Since we still stand strong to [our opinion against GooglePlay](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store), we want to upload an Installer that does the following things:

1. App has to have the same HD Icon like ours has
2. Upon clicking it, a window shows a `DOWNLOAD` button
3. App checks if either Aptoide and/or F-Droid or no store at all is installed
4. If Aptoide is installed, it shall add [our Aptoide store](http://aimsicd.store.aptoide.com/) and install AIMSICD from there
5. If F-Droid is installed, it shall fetch AIMSICD from [there](https://f-droid.org/repository/browse/?fdid=com.SecUpwN.AIMSICD) and continue to install it
6. If both stores are installed, Aptoide will be preferred
7. If no store at all is installed, the App shall grab the [latest GitHub Release](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases) and install it

Does that sound like a good solution to this problem, @E3V3A and @He3556?

**Comment by E3V3A** [comment] 2015-02-27 20:46
Sound excellent!  The downloader app should also display the signature of the downloaded version for easy verification with our GitHub releases.

**Comment by SecUpwN** [comment] 2015-03-01 18:10
@E3V3A, I would like to keep development of the downloader app on our GitHub here as well. Shall I add a new branch for this or what would you prefer?

**Comment by E3V3A** [comment] 2015-03-01 22:23
That's not a new branch, that would be a new repo. See internal chat.

**Comment by SecUpwN** [comment] 2015-05-02 18:07
With [more bad news of Google](http://boingboing.net/2015/04/28/fbis-crypto-backdoor-plans-r.html) turning up, we've finally **DITCHED** this idea. Please do **NOT** upload our app on GooglePlay (not even as a re-branded installer) and carefully read [our statement](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store). Thank you!

**Closed** 2015-05-02 18:07 UTC
Labels: DEPLOYMENT, DEV_DISCUSSION, REMEMBER_THIS

**Comment by TPS** [comment] 2015-08-07 02:42
@SecUpwN https://play.google.com/store/apps/details?id=com.SecUpwN.AIMSICD is still live. =(

**Comment by E3V3A** [comment] 2015-08-07 08:15
And [blatant copies](https://play.google.com/store/apps/details?id=kz.galan.antispy)...without any cred references.

**Comment by TPS** [comment] 2015-08-07 15:07
For the record, (& I *have* followed all the arguments from the beginning) not having an official presence on GPlay encourages this kind of misbehavior, & also makes it harder to enforce claims of IP infringement.

**Comment by E3V3A** [comment] 2015-08-08 06:36
The issue is that we *would like* to have an installer presence in GP, but that we: (a) Refuse to pay for it while (b) give up our anonymity in the process.  If any one of our trusted developers feel he's got nothing to loose here, they're certainly free to make it such.

**Comment by TPS** [comment] 2015-08-08 07:28
I'm not disagreeing with any of that; just pointing out Google's rules favor them*selves* 1st, even above AICD's intellectual property rights.

Other than tagging these IP infringement while in Play Store, is there a more effective way to complain?

**Comment by TPS** [comment] 2015-08-08 21:56
> Other than tagging these IP infringement while in Play Store, is there a more effective way to complain?

I guess there is:
https://support.google.com/legal/troubleshooter/1114905

But this has to be done by the official "copyright holder."  Is this you, @SecUpwN?

**Comment by elfevenfairy** [comment] 2015-08-09 07:08
no it's not me

**Comment by SecUpwN** [comment] 2015-08-09 15:20
>@SecUpwN https://play.google.com/store/apps/details?id=com.SecUpwN.AIMSICD is still live. =(

Thanks for notifying me, @TPS. I can't visit the URL, it seems to have been taken down already.

>And [blatant copies](https://play.google.com/store/apps/details?id=kz.galan.antispy)...without any cred references.

I have been writing a message to that guy already to stop copying our work and respecting the GPL - without any effect. Thanks to the link of @TPS, I just filed a copyright infringement. And to be honest: I am pretty sick of this shit and keep playing with the thought of giving up and providing our app on this shitty GPlay store - but then again, I am *very* reluctant to even see it there, even if someone else would do it!

**Comment by TPS** [comment] 2015-08-09 19:12
@SecUpwN I think it's **_not_** taken down; I think the guy blocked your country or something, as *I* can directly get to it from the link still.  This guy really frosts me! :rage:  It's obviously still worth filing on that 1st 1, then.…

**Comment by SecUpwN** [comment] 2015-08-09 21:49
>This guy really frosts me! (Since especially he doesn't update nor give credit.)

@TPS, I am quite happy that he does not update. Other than that,  hereby grant permission to you to act on my behalf and file a proper and well-written copyright infringement on that copy. For the future, I guess we should find someone working for GooglePlay and being able to remove stuff if we tell him/her.

**Comment by TPS** [comment] 2015-08-10 00:45
@SecUpwN 
> I am quite happy that he does not update.

Problem with that is that most people will then find _that_ version of AICD first when searching for in the their logical starting place — Google Play.  99% of people would never even think to look further, &, when they've problems, then they'll rate AICD poorly, which ends up in Google search ratings, which ruins this project' (& all its hard-working devs') reputation.  It took me _months_ to discover the Play store "version" wasn't official!

Regardless, I'm happy to file the report on your behalf.  Do you have a copy of the report you already filed, to avoid missing anything important?  Else, I will post here with what I come up with before I submit to get feedback, ok?

**Comment by SecUpwN** [comment] 2015-08-10 05:31
@TPS, I do get the point regarding our reputation and I feel the need for our project to hack around the GooglePlay privacy breaches. If there was a way for to regsiter an account without spending money and losing privacy, I'd create an official one ASAP - feel free to help me digging one up and send it to my email address. Other than that, I have not kept a copy of my report. Just explain in simple words what you just mentioned and maybe even link to this discussion, if you wish.

>Else, I will post here, with what I come up with before I submit, to get feedback, ok?

No, please don't. I want avoid to resurrect this Issue from the dead. Too many people involved. And just to mention it: Our app is called "AIMSICD" in short, not "AICD" - please use that in further postings. ;-)

**Comment by vanitasvitae** [comment] 2016-01-25 01:13
Have you thought about adding the fact, that AIMSICD is not available in the PlayStore, to the app itself? That way a user who wants to tell other people about the app is reminded to tell them where (not) to look for the app.

**Comment by SecUpwN** [comment] 2016-01-25 07:31
>Have you thought about adding the fact, that AIMSICD is not available in the PlayStore, to the app itself?

@vanitasvitae, it is mentioned everywhere across our project and we also linked [this FAQ entry](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store). Feel invited to craft a pull request if you like to see an improvment on our aöp somewhere. Thank you.
